name: Run Web Crawler

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分鐘執行一次
  workflow_dispatch:     # 手動觸發

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r crawler/requirements.txt

    - name: Run crawler script
      run: python crawler/main.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add personData.json
        git commit -m "update personData by crawler" || echo "No changes to commit"
        git push
